# HTTP
quarkus.http.port=8080
quarkus.http.cors=true
quarkus.http.cors.origins=${ALLOWED_ORIGINS:*}
quarkus.http.limits.max-body-size=15M

# AWS S3
quarkus.s3.aws.region=${AWS_REGION:us-east-1}
quarkus.s3.aws.credentials.type=static
quarkus.s3.aws.credentials.static-provider.access-key-id=${AWS_ACCESS_KEY_ID:test}
quarkus.s3.aws.credentials.static-provider.secret-access-key=${AWS_SECRET_ACCESS_KEY:test}
quarkus.s3.endpoint-override=${S3_ENDPOINT_INTERNAL:${S3_ENDPOINT:http://localhost:4566}}
quarkus.s3.path-style-access=true

# AWS SQS
quarkus.sqs.aws.region=${AWS_REGION:us-east-1}
quarkus.sqs.aws.credentials.type=static
quarkus.sqs.aws.credentials.static-provider.access-key-id=${AWS_ACCESS_KEY_ID:test}
quarkus.sqs.aws.credentials.static-provider.secret-access-key=${AWS_SECRET_ACCESS_KEY:test}
quarkus.sqs.endpoint-override=${SQS_ENDPOINT:http://localhost:4566}

# Elasticsearch
quarkus.elasticsearch.hosts=${ES_URL:localhost:9200}

# Application Config
clipsearch.s3.bucket=${S3_BUCKET:clipsearch}
clipsearch.sqs.queue=${SQS_QUEUE_NAME:clipsearch-index-queue}

# Always enable Swagger UI (even in prod/docker)
quarkus.swagger-ui.always-include=true