apiVersion: v1
kind: ConfigMap
metadata:
  name: clipsearch-config
data:
  S3_ENDPOINT: "http://localstack:4566"
  SQS_ENDPOINT: "http://localstack:4566"
  ES_URL: "elasticsearch:9200"
  S3_BUCKET: "clipsearch"
  SQS_QUEUE_NAME: "clipsearch-index-queue"
  ALLOWED_ORIGINS: "*"
  RHOAI_BASE_URL: "http://llm-model:80/v1"
  RHOAI_MODEL_NAME: "llm-model"
  AI_ENABLED: "true"
