apiVersion: v1
kind: ConfigMap
metadata:
  name: clipsearch-config
data:
  S3_ENDPOINT: "https://localstack-dawidbera-dev.apps.rm2.thpm.p1.openshiftapps.com"
  CLIPSEARCH_PUBLIC_S3_ENDPOINT: "https://localstack-dawidbera-dev.apps.rm2.thpm.p1.openshiftapps.com"
  S3_ENDPOINT_INTERNAL: "http://localstack:4566"
  SQS_ENDPOINT: "http://localstack:4566"
  ES_URL: "elasticsearch:9200"
  S3_BUCKET: "clipsearch"
  SQS_QUEUE_NAME: "clipsearch-index-queue"
  ALLOWED_ORIGINS: "*"
  RHOAI_BASE_URL: "http://llm-standalone.dawidbera-dev.svc.cluster.local:80/v1"
  RHOAI_MODEL_NAME: "tinyllama"
  AI_ENABLED: "true"
