apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - config.yaml
  - localstack.yaml
  - localstack-route.yaml
  - localstack-init.yaml
  - elasticsearch.yaml
  - api.yaml
  - worker.yaml
  - frontend.yaml
